services:
    micro_email:
        build:
            args:
                user: icaro
                uid: 1000
            context: ./
            dockerfile: ./Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes: 
            - ./:/var/www
        depends_on:
            - micro_email_redis
        networks:
            - microservices          
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8007:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - microservices

    micro_email_queue:
        build:
            args:
                user: icaro
                uid: 1000
            context: ./
            dockerfile: Dockerfile 
        command: "php artisan queue:work --verbose --tries=3 --timeout=60"
        restart: unless-stopped
        volumes:
            - ./:/var/www
        depends_on:
            - micro_email_redis
        networks:
            - microservices           
    micro_email_redis:
        image: redis:latest
        ports:
          - 6380:6379
        networks:
            - microservices                      
networks:
  microservices:
      driver: bridge